# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - app/*
    - gradle/*
    - metadata/*
    - azure-pipelines.yml
    - build.gradle
    - gradle.properties
    - gradlew
    - gradlew.bat
    - settings.gradle

jobs:
- job: bundle
  displayName: 'Build bundle'
  pool:
    vmImage: 'macos-latest'
  steps:
    - task: Gradle@2
      displayName: 'build bundle'
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'bundleRelease'
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        gradleOptions: '-Xmx3072m'
        sonarQubeRunAnalysis: false

    - task: AndroidSigning@2
      displayName: 'sign bundle'
      inputs:
        apkFiles: '**/*.aab'
        jarsign: true
        jarsignerKeystoreFile: 'mygradesreloaded.jks'
        jarsignerKeystorePassword: '$(jarsignerKeyPassword)'
        jarsignerKeystoreAlias: 'mygradesreloaded.upload'
        jarsignerKeyPassword: '$(jarsignerKeyPassword)'
        jarsignerArguments: '-sigalg SHA256withRSA -digestalg SHA-256'
        zipalign: true

    - task: CopyFiles@2
      inputs:
        SourceFolder: $(Build.SourcesDirectory)
        contents: '**/*.aab'
        targetFolder: '$(build.artifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/app/build/outputs/bundle/release'
        artifactName: 'bundle-files'
        artifactType: 'container'

    - task: CopyFiles@2
      inputs:
        SourceFolder: $(Build.SourcesDirectory)
        contents: 'metadata/**'
        targetFolder: '$(build.artifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/metadata/android/**'
        artifactName: 'metadata-files'
        artifactType: 'container'




- job: apk
  displayName: 'Build APK'
  pool:
    vmImage: 'macos-latest'
  steps:
    - task: Gradle@2
      displayName: 'build apk'
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'assembleRelease'
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        gradleOptions: '-Xmx3072m'
        sonarQubeRunAnalysis: false

    - task: AndroidSigning@2
      displayName: 'sign apk'
      inputs:
        apkFiles: '**/*.apk'
        jarsign: true
        jarsignerKeystoreFile: 'mygradesreloaded.jks'
        jarsignerKeystorePassword: '$(jarsignerKeyPassword)'
        jarsignerKeystoreAlias: 'mygradesreloaded.upload'
        jarsignerKeyPassword: '$(jarsignerKeyPassword)'
        zipalign: true

    - task: CopyFiles@2
      inputs:
        SourceFolder: $(Build.SourcesDirectory)
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/app/build/outputs/apk/release/'
        artifactName: 'apk-files'
        artifactType: 'container'
