# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:

- task: Gradle@2
  displayName: 'gradlew build'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'bundleRelease'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false

- task: AndroidSigning@2
  inputs:
    apkFiles: '**/*.aab'
    jarsign: true
    jarsignerKeystoreFile: 'mygradesreloaded.jks'
    jarsignerKeystorePassword: '$(jarsignerKeyPassword)'
    jarsignerKeystoreAlias: 'mygradesreloaded.upload'
    jarsignerKeyPassword: '$(jarsignerKeyPassword)'
    zipalign: true

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.SourcesDirectory)
    contents: '**/*.aab'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/app/build/outputs/bundle/release'
    artifactName: 'apk-files'
    artifactType: 'container'