package de.mygrades.database.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ACTION_PARAM".
 */
public class ActionParam {

    private Long actionParamId;
    /** Not-null value. */
    private String key;
    private String value;
    private String type;
    private long actionId;

    public ActionParam() {
    }

    public ActionParam(Long actionParamId) {
        this.actionParamId = actionParamId;
    }

    public ActionParam(Long actionParamId, String key, String value, String type, long actionId) {
        this.actionParamId = actionParamId;
        this.key = key;
        this.value = value;
        this.type = type;
        this.actionId = actionId;
    }

    public Long getActionParamId() {
        return actionParamId;
    }

    public void setActionParamId(Long actionParamId) {
        this.actionParamId = actionParamId;
    }

    /** Not-null value. */
    public String getKey() {
        return key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(String key) {
        this.key = key;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public long getActionId() {
        return actionId;
    }

    public void setActionId(long actionId) {
        this.actionId = actionId;
    }


    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return "ActionParam{" +
                "actionParamId=" + actionParamId +
                ", key='" + key + '\'' +
                ", value='" + value + '\'' +
                ", type='" + type + '\'' +
                ", actionId=" + actionId +
                '}';
    }


    // KEEP METHODS END
}
