package de.mygrades.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import de.mygrades.database.dao.GradeEntry;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GRADE_ENTRY".
*/
public class GradeEntryDao extends AbstractDao<GradeEntry, Void> {

    public static final String TABLENAME = "GRADE_ENTRY";

    /**
     * Properties of entity GradeEntry.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Name = new Property(0, String.class, "name", false, "NAME");
        public final static Property Grade = new Property(1, Double.class, "grade", false, "GRADE");
        public final static Property ExamId = new Property(2, String.class, "examId", false, "EXAM_ID");
        public final static Property Semester = new Property(3, String.class, "semester", false, "SEMESTER");
        public final static Property State = new Property(4, String.class, "state", false, "STATE");
        public final static Property CreditPoints = new Property(5, Double.class, "creditPoints", false, "CREDIT_POINTS");
        public final static Property SemesterNumber = new Property(6, Integer.class, "semesterNumber", false, "SEMESTER_NUMBER");
    };


    public GradeEntryDao(DaoConfig config) {
        super(config);
    }
    
    public GradeEntryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GRADE_ENTRY\" (" + //
                "\"NAME\" TEXT NOT NULL ," + // 0: name
                "\"GRADE\" REAL," + // 1: grade
                "\"EXAM_ID\" TEXT," + // 2: examId
                "\"SEMESTER\" TEXT NOT NULL ," + // 3: semester
                "\"STATE\" TEXT," + // 4: state
                "\"CREDIT_POINTS\" REAL," + // 5: creditPoints
                "\"SEMESTER_NUMBER\" INTEGER);"); // 6: semesterNumber
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GRADE_ENTRY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GradeEntry entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getName());
 
        Double grade = entity.getGrade();
        if (grade != null) {
            stmt.bindDouble(2, grade);
        }
 
        String examId = entity.getExamId();
        if (examId != null) {
            stmt.bindString(3, examId);
        }
        stmt.bindString(4, entity.getSemester());
 
        String state = entity.getState();
        if (state != null) {
            stmt.bindString(5, state);
        }
 
        Double creditPoints = entity.getCreditPoints();
        if (creditPoints != null) {
            stmt.bindDouble(6, creditPoints);
        }
 
        Integer semesterNumber = entity.getSemesterNumber();
        if (semesterNumber != null) {
            stmt.bindLong(7, semesterNumber);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public GradeEntry readEntity(Cursor cursor, int offset) {
        GradeEntry entity = new GradeEntry( //
            cursor.getString(offset + 0), // name
            cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1), // grade
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // examId
            cursor.getString(offset + 3), // semester
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // state
            cursor.isNull(offset + 5) ? null : cursor.getDouble(offset + 5), // creditPoints
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6) // semesterNumber
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GradeEntry entity, int offset) {
        entity.setName(cursor.getString(offset + 0));
        entity.setGrade(cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1));
        entity.setExamId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSemester(cursor.getString(offset + 3));
        entity.setState(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCreditPoints(cursor.isNull(offset + 5) ? null : cursor.getDouble(offset + 5));
        entity.setSemesterNumber(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(GradeEntry entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(GradeEntry entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
