package de.mygrades.database.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import de.mygrades.database.dao.Rule;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RULE".
*/
public class RuleDao extends AbstractDao<Rule, Long> {

    public static final String TABLENAME = "RULE";

    /**
     * Properties of entity Rule.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property RuleId = new Property(0, Long.class, "ruleId", true, "RULE_ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property SemesterFormat = new Property(2, String.class, "semesterFormat", false, "SEMESTER_FORMAT");
        public final static Property SemesterPattern = new Property(3, String.class, "semesterPattern", false, "SEMESTER_PATTERN");
        public final static Property SemesterStartSummer = new Property(4, Integer.class, "semesterStartSummer", false, "SEMESTER_START_SUMMER");
        public final static Property SemesterStartWinter = new Property(5, Integer.class, "semesterStartWinter", false, "SEMESTER_START_WINTER");
        public final static Property GradeFactor = new Property(6, Double.class, "gradeFactor", false, "GRADE_FACTOR");
        public final static Property LastUpdated = new Property(7, java.util.Date.class, "lastUpdated", false, "LAST_UPDATED");
        public final static Property Overview = new Property(8, Boolean.class, "overview", false, "OVERVIEW");
        public final static Property Type = new Property(9, String.class, "type", false, "TYPE");
        public final static Property UniversityId = new Property(10, long.class, "universityId", false, "UNIVERSITY_ID");
    };

    private DaoSession daoSession;

    private Query<Rule> university_RulesQuery;

    public RuleDao(DaoConfig config) {
        super(config);
    }
    
    public RuleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RULE\" (" + //
                "\"RULE_ID\" INTEGER PRIMARY KEY ," + // 0: ruleId
                "\"NAME\" TEXT NOT NULL ," + // 1: name
                "\"SEMESTER_FORMAT\" TEXT," + // 2: semesterFormat
                "\"SEMESTER_PATTERN\" TEXT," + // 3: semesterPattern
                "\"SEMESTER_START_SUMMER\" INTEGER," + // 4: semesterStartSummer
                "\"SEMESTER_START_WINTER\" INTEGER," + // 5: semesterStartWinter
                "\"GRADE_FACTOR\" REAL," + // 6: gradeFactor
                "\"LAST_UPDATED\" INTEGER," + // 7: lastUpdated
                "\"OVERVIEW\" INTEGER," + // 8: overview
                "\"TYPE\" TEXT," + // 9: type
                "\"UNIVERSITY_ID\" INTEGER NOT NULL );"); // 10: universityId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RULE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Rule entity) {
        stmt.clearBindings();
 
        Long ruleId = entity.getRuleId();
        if (ruleId != null) {
            stmt.bindLong(1, ruleId);
        }
        stmt.bindString(2, entity.getName());
 
        String semesterFormat = entity.getSemesterFormat();
        if (semesterFormat != null) {
            stmt.bindString(3, semesterFormat);
        }
 
        String semesterPattern = entity.getSemesterPattern();
        if (semesterPattern != null) {
            stmt.bindString(4, semesterPattern);
        }
 
        Integer semesterStartSummer = entity.getSemesterStartSummer();
        if (semesterStartSummer != null) {
            stmt.bindLong(5, semesterStartSummer);
        }
 
        Integer semesterStartWinter = entity.getSemesterStartWinter();
        if (semesterStartWinter != null) {
            stmt.bindLong(6, semesterStartWinter);
        }
 
        Double gradeFactor = entity.getGradeFactor();
        if (gradeFactor != null) {
            stmt.bindDouble(7, gradeFactor);
        }
 
        java.util.Date lastUpdated = entity.getLastUpdated();
        if (lastUpdated != null) {
            stmt.bindLong(8, lastUpdated.getTime());
        }
 
        Boolean overview = entity.getOverview();
        if (overview != null) {
            stmt.bindLong(9, overview ? 1L: 0L);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(10, type);
        }
        stmt.bindLong(11, entity.getUniversityId());
    }

    @Override
    protected void attachEntity(Rule entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Rule readEntity(Cursor cursor, int offset) {
        Rule entity = new Rule( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ruleId
            cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // semesterFormat
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // semesterPattern
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // semesterStartSummer
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // semesterStartWinter
            cursor.isNull(offset + 6) ? null : cursor.getDouble(offset + 6), // gradeFactor
            cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)), // lastUpdated
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0, // overview
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // type
            cursor.getLong(offset + 10) // universityId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Rule entity, int offset) {
        entity.setRuleId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setSemesterFormat(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSemesterPattern(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSemesterStartSummer(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setSemesterStartWinter(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setGradeFactor(cursor.isNull(offset + 6) ? null : cursor.getDouble(offset + 6));
        entity.setLastUpdated(cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)));
        entity.setOverview(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0);
        entity.setType(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setUniversityId(cursor.getLong(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Rule entity, long rowId) {
        entity.setRuleId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Rule entity) {
        if(entity != null) {
            return entity.getRuleId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "rules" to-many relationship of University. */
    public List<Rule> _queryUniversity_Rules(long universityId) {
        synchronized (this) {
            if (university_RulesQuery == null) {
                QueryBuilder<Rule> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.UniversityId.eq(null));
                university_RulesQuery = queryBuilder.build();
            }
        }
        Query<Rule> query = university_RulesQuery.forCurrentThread();
        query.setParameter(0, universityId);
        return query.list();
    }

}
