package de.mygrades.database.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TRANSFORMER_MAPPING".
 */
public class TransformerMapping {

    private Long id;
    /** Not-null value. */
    private String name;
    private String parseExpression;
    private String parseType;
    private long ruleId;

    public TransformerMapping() {
    }

    public TransformerMapping(Long id) {
        this.id = id;
    }

    public TransformerMapping(Long id, String name, String parseExpression, String parseType, long ruleId) {
        this.id = id;
        this.name = name;
        this.parseExpression = parseExpression;
        this.parseType = parseType;
        this.ruleId = ruleId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getParseExpression() {
        return parseExpression;
    }

    public void setParseExpression(String parseExpression) {
        this.parseExpression = parseExpression;
    }

    public String getParseType() {
        return parseType;
    }

    public void setParseType(String parseType) {
        this.parseType = parseType;
    }

    public long getRuleId() {
        return ruleId;
    }

    public void setRuleId(long ruleId) {
        this.ruleId = ruleId;
    }

}
