package dh.mygrades.database.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ACTION_PARAM".
*/
public class ActionParamDao extends AbstractDao<ActionParam, Long> {

    public static final String TABLENAME = "ACTION_PARAM";

    /**
     * Properties of entity ActionParam.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ActionParamId = new Property(0, Long.class, "actionParamId", true, "ACTION_PARAM_ID");
        public final static Property Key = new Property(1, String.class, "key", false, "KEY");
        public final static Property Value = new Property(2, String.class, "value", false, "VALUE");
        public final static Property Type = new Property(3, String.class, "type", false, "TYPE");
        public final static Property ActionId = new Property(4, long.class, "actionId", false, "ACTION_ID");
    };

    private Query<ActionParam> action_ActionParamsQuery;

    public ActionParamDao(DaoConfig config) {
        super(config);
    }
    
    public ActionParamDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ACTION_PARAM\" (" + //
                "\"ACTION_PARAM_ID\" INTEGER PRIMARY KEY ," + // 0: actionParamId
                "\"KEY\" TEXT NOT NULL ," + // 1: key
                "\"VALUE\" TEXT," + // 2: value
                "\"TYPE\" TEXT," + // 3: type
                "\"ACTION_ID\" INTEGER NOT NULL );"); // 4: actionId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ACTION_PARAM\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ActionParam entity) {
        stmt.clearBindings();
 
        Long actionParamId = entity.getActionParamId();
        if (actionParamId != null) {
            stmt.bindLong(1, actionParamId);
        }
        stmt.bindString(2, entity.getKey());
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(3, value);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(4, type);
        }
        stmt.bindLong(5, entity.getActionId());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ActionParam readEntity(Cursor cursor, int offset) {
        ActionParam entity = new ActionParam( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // actionParamId
            cursor.getString(offset + 1), // key
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // value
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // type
            cursor.getLong(offset + 4) // actionId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ActionParam entity, int offset) {
        entity.setActionParamId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKey(cursor.getString(offset + 1));
        entity.setValue(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setType(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setActionId(cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ActionParam entity, long rowId) {
        entity.setActionParamId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ActionParam entity) {
        if(entity != null) {
            return entity.getActionParamId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "actionParams" to-many relationship of Action. */
    public List<ActionParam> _queryAction_ActionParams(long actionId) {
        synchronized (this) {
            if (action_ActionParamsQuery == null) {
                QueryBuilder<ActionParam> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ActionId.eq(null));
                action_ActionParamsQuery = queryBuilder.build();
            }
        }
        Query<ActionParam> query = action_ActionParamsQuery.forCurrentThread();
        query.setParameter(0, actionId);
        return query.list();
    }

}
