package dh.mygrades.database.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig universityDaoConfig;
    private final DaoConfig ruleDaoConfig;
    private final DaoConfig actionDaoConfig;
    private final DaoConfig actionParamDaoConfig;
    private final DaoConfig transformerMappingDaoConfig;
    private final DaoConfig gradeEntryDaoConfig;
    private final DaoConfig overviewDaoConfig;

    private final UniversityDao universityDao;
    private final RuleDao ruleDao;
    private final ActionDao actionDao;
    private final ActionParamDao actionParamDao;
    private final TransformerMappingDao transformerMappingDao;
    private final GradeEntryDao gradeEntryDao;
    private final OverviewDao overviewDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        universityDaoConfig = daoConfigMap.get(UniversityDao.class).clone();
        universityDaoConfig.initIdentityScope(type);

        ruleDaoConfig = daoConfigMap.get(RuleDao.class).clone();
        ruleDaoConfig.initIdentityScope(type);

        actionDaoConfig = daoConfigMap.get(ActionDao.class).clone();
        actionDaoConfig.initIdentityScope(type);

        actionParamDaoConfig = daoConfigMap.get(ActionParamDao.class).clone();
        actionParamDaoConfig.initIdentityScope(type);

        transformerMappingDaoConfig = daoConfigMap.get(TransformerMappingDao.class).clone();
        transformerMappingDaoConfig.initIdentityScope(type);

        gradeEntryDaoConfig = daoConfigMap.get(GradeEntryDao.class).clone();
        gradeEntryDaoConfig.initIdentityScope(type);

        overviewDaoConfig = daoConfigMap.get(OverviewDao.class).clone();
        overviewDaoConfig.initIdentityScope(type);

        universityDao = new UniversityDao(universityDaoConfig, this);
        ruleDao = new RuleDao(ruleDaoConfig, this);
        actionDao = new ActionDao(actionDaoConfig, this);
        actionParamDao = new ActionParamDao(actionParamDaoConfig, this);
        transformerMappingDao = new TransformerMappingDao(transformerMappingDaoConfig, this);
        gradeEntryDao = new GradeEntryDao(gradeEntryDaoConfig, this);
        overviewDao = new OverviewDao(overviewDaoConfig, this);

        registerDao(University.class, universityDao);
        registerDao(Rule.class, ruleDao);
        registerDao(Action.class, actionDao);
        registerDao(ActionParam.class, actionParamDao);
        registerDao(TransformerMapping.class, transformerMappingDao);
        registerDao(GradeEntry.class, gradeEntryDao);
        registerDao(Overview.class, overviewDao);
    }
    
    public void clear() {
        universityDaoConfig.getIdentityScope().clear();
        ruleDaoConfig.getIdentityScope().clear();
        actionDaoConfig.getIdentityScope().clear();
        actionParamDaoConfig.getIdentityScope().clear();
        transformerMappingDaoConfig.getIdentityScope().clear();
        gradeEntryDaoConfig.getIdentityScope().clear();
        overviewDaoConfig.getIdentityScope().clear();
    }

    public UniversityDao getUniversityDao() {
        return universityDao;
    }

    public RuleDao getRuleDao() {
        return ruleDao;
    }

    public ActionDao getActionDao() {
        return actionDao;
    }

    public ActionParamDao getActionParamDao() {
        return actionParamDao;
    }

    public TransformerMappingDao getTransformerMappingDao() {
        return transformerMappingDao;
    }

    public GradeEntryDao getGradeEntryDao() {
        return gradeEntryDao;
    }

    public OverviewDao getOverviewDao() {
        return overviewDao;
    }

}
